# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/CodeTry/CODExperiment/Lab5/project_1/project_1.srcs/sources_1/ip/DataMem/DataMem.xci
# IP: The module: 'DataMem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CodeTry/CODExperiment/Lab5/project_1/project_1.srcs/sources_1/ip/DataMem/DataMem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DataMem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/CodeTry/CODExperiment/Lab5/project_1/project_1.srcs/sources_1/ip/DataMem/DataMem.xci
# IP: The module: 'DataMem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CodeTry/CODExperiment/Lab5/project_1/project_1.srcs/sources_1/ip/DataMem/DataMem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DataMem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
