# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CodeTry/CODExperiment/Lab4/project_1/project_1.srcs/sources_1/ip/Data_Mem_DualPorts/Data_Mem_DualPorts.xci
# IP: The module: 'Data_Mem_DualPorts' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CodeTry/CODExperiment/Lab4/project_1/project_1.srcs/sources_1/ip/Data_Mem_DualPorts/Data_Mem_DualPorts_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_Mem_DualPorts'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/CodeTry/CODExperiment/Lab4/project_1/project_1.srcs/sources_1/ip/Data_Mem_DualPorts/Data_Mem_DualPorts.xci
# IP: The module: 'Data_Mem_DualPorts' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CodeTry/CODExperiment/Lab4/project_1/project_1.srcs/sources_1/ip/Data_Mem_DualPorts/Data_Mem_DualPorts_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_Mem_DualPorts'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
