# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/CodeTry/CODExperiment/Lab5/Nexys4DDR.xdc

# IP: ip/InstMem/InstMem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==InstMem || ORIG_REF_NAME==InstMem} -quiet] -quiet
