# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Code Try/CODExperiment/Lab2/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_256_16_RF/blk_mem_gen_256_16_RF.xci
# IP: The module: 'blk_mem_gen_256_16_RF' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Code Try/CODExperiment/Lab2/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_256_16_RF/blk_mem_gen_256_16_RF_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_256_16_RF'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Code Try/CODExperiment/Lab2/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_256_16_RF/blk_mem_gen_256_16_RF.xci
# IP: The module: 'blk_mem_gen_256_16_RF' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Code Try/CODExperiment/Lab2/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_256_16_RF/blk_mem_gen_256_16_RF_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_256_16_RF'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
