# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Code Try/CODExperiment/Lab2/project_1/project_1.srcs/sources_1/ip/DRAM_4096_16/DRAM_4096_16.xci
# IP: The module: 'DRAM_4096_16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Code Try/CODExperiment/Lab2/project_1/project_1.srcs/sources_1/ip/DRAM_4096_16/DRAM_4096_16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DRAM_4096_16'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Code Try/CODExperiment/Lab2/project_1/project_1.srcs/sources_1/ip/DRAM_4096_16/DRAM_4096_16.xci
# IP: The module: 'DRAM_4096_16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Code Try/CODExperiment/Lab2/project_1/project_1.srcs/sources_1/ip/DRAM_4096_16/DRAM_4096_16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DRAM_4096_16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
